[project]
name = "atl_util"
version = "0.1"

dependencies = [
    "atlassian-python-api @ git+https://github.com/brownterryn/atlassian-python-api.git",
    "python-dotenv",
    "lxml",
    "inquirer",
    "requests",
]
